// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk8pkWifz2kB8mlBaaAVp1-5Q5Qw4S7yQ',
    appId: '1:220656551479:web:8b9576a9a7d99576e721b2',
    messagingSenderId: '220656551479',
    projectId: 'otpt2-c21dd',
    authDomain: 'otpt2-c21dd.firebaseapp.com',
    storageBucket: 'otpt2-c21dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXO_4cqouRdXT0aoUPuW-7T0qscRzgPbU',
    appId: '1:220656551479:android:c6fd8ca3af173341e721b2',
    messagingSenderId: '220656551479',
    projectId: 'otpt2-c21dd',
    storageBucket: 'otpt2-c21dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBBu17of-TDnjqGHNz7m-PscexHy8_94',
    appId: '1:220656551479:ios:c4d42cc88331322ce721b2',
    messagingSenderId: '220656551479',
    projectId: 'otpt2-c21dd',
    storageBucket: 'otpt2-c21dd.appspot.com',
    iosBundleId: 'com.example.varificationtrail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBBu17of-TDnjqGHNz7m-PscexHy8_94',
    appId: '1:220656551479:ios:c4d42cc88331322ce721b2',
    messagingSenderId: '220656551479',
    projectId: 'otpt2-c21dd',
    storageBucket: 'otpt2-c21dd.appspot.com',
    iosBundleId: 'com.example.varificationtrail2',
  );
}
